using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MediatR;
using Microsoft.Extensions.Logging;
using PlanWriter.Application.Milestones.Dtos.Queries;
using PlanWriter.Domain.Dtos;
using PlanWriter.Domain.Entities;
using PlanWriter.Domain.Interfaces.ReadModels.Milestones;
using PlanWriter.Domain.Interfaces.ReadModels.Projects;
using PlanWriter.Domain.Interfaces.Repositories;

namespace PlanWriter.Application.Milestones.Queries;

public class GetProjectMilestonesQueryHandler(
    ILogger<GetProjectMilestonesQueryHandler> logger,
    IMilestonesReadRepository milestonesReadRepository,
    IProjectReadRepository projectReadRepository)
    : IRequestHandler<GetProjectMilestonesQuery, List<MilestoneDto>>
{
    public async Task<List<MilestoneDto>> Handle(GetProjectMilestonesQuery request, CancellationToken cancellationToken)
    {
        logger.LogInformation("Getting milestones for Project {ProjectId} and User {UserId}", request.ProjectId, request.UserId);
       
        var project = await projectReadRepository.GetUserProjectByIdAsync(request.ProjectId, request.UserId, cancellationToken)
            ?? throw new UnauthorizedAccessException("Projeto não encontrado.");

        logger.LogInformation("Access to Project {ProjectId} granted for User {UserId}", request.ProjectId, request.UserId);
        
        var projectMilestones = await milestonesReadRepository.GetByProjectIdAsync(request.ProjectId, cancellationToken);

        logger.LogInformation("Found {Count} milestones for Project {ProjectId}", projectMilestones.Count, request.ProjectId);
       
        return projectMilestones
            .OrderBy(milestone => milestone.Order)
            .Select(MapToMilestoneDto)
            .ToList();
    }

    /* ===================== PRIVATE METHODS ===================== */

    private static MilestoneDto MapToMilestoneDto(Milestone milestone)
    {
        return new MilestoneDto
        {
            Id = milestone.Id,
            ProjectId = milestone.ProjectId,
            Name = milestone.Name,
            TargetAmount = milestone.TargetAmount,
            Order = milestone.Order,
            DueDate = milestone.DueDate,
            Notes = milestone.Notes,
            AutoGenerated = milestone.AutoGenerated,
            Completed = milestone.Completed,
            CreatedAt = milestone.CreatedAt
        };
    }
}
