using System;

namespace PlanWriter.Domain.Entities;

public class Milestone
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ProjectId { get; set; }
    public Project Project { get; set; } = default!;

    public string Name { get; set; } = string.Empty;   // ex.: “25%”
    public int TargetAmount { get; set; }              // alvo na unidade do projeto
    public int Order { get; set; }                     // ordenação
    public DateTime? DueDate { get; set; }             // opcional
    public bool AutoGenerated { get; set; }            // 25/50/75/100
    public DateTime? AchievedAtUtc { get; set; }       // quando atingiu
    public string? Notes { get; set; }
    public DateTime CreatedAt { get; set; }
    public bool Completed { get; set; }
    public DateTime? CompletedAt { get; set; }
}