using System;

namespace PlanWriter.Domain.Dtos;

public class MilestoneDto
{
    public Guid Id { get; set; }
    public Guid ProjectId { get; set; }

    public string Name { get; set; } = null!;
    public int TargetAmount { get; set; }

    public int Order { get; set; }
    public DateTime? DueDate { get; set; }

    public string? Notes { get; set; }

    public bool AutoGenerated { get; set; }
    public bool Completed { get; set; }
    public DateTime CreatedAt { get; set; }
}