using System;
using System.Threading;
using System.Threading.Tasks;
using MediatR;
using Microsoft.Extensions.Logging;
using PlanWriter.Application.Milestones.Dtos.Commands;
using PlanWriter.Domain.Dtos;
using PlanWriter.Domain.Entities;
using PlanWriter.Domain.Interfaces.ReadModels.Milestones;
using PlanWriter.Domain.Interfaces.ReadModels.Projects;
using PlanWriter.Domain.Interfaces.Repositories;

namespace PlanWriter.Application.Milestones.Commands;

public class CreateMilestoneCommandHandler(
    ILogger<CreateMilestoneCommandHandler> logger,
    IMilestonesRepository milestonesRepository,
    IProjectReadRepository projectReadRepository,
    IMilestonesReadRepository milestonesReadRepository
) : IRequestHandler<CreateMilestoneCommand, MilestoneDto>
{
    public async Task<MilestoneDto> Handle(CreateMilestoneCommand request, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(request);

        if (request.Dto.TargetAmount <= 0)
            throw new ArgumentException("TargetAmount must be greater than zero.");

        logger.LogInformation(
            "Creating milestone for project {ProjectId} by user {UserId}",
            request.ProjectId,
            request.UserId
        );

        // garante que o projeto pertence ao usuário
        var project = await projectReadRepository
                          .GetUserProjectByIdAsync(request.ProjectId, request.UserId, ct)
                      ?? throw new UnauthorizedAccessException("Project not found.");

        // resolve ordem
        var order = request.Dto.Order
                    ?? await milestonesReadRepository.GetNextOrderAsync(request.ProjectId, ct);

        var milestone = BuildMilestone(request, order);

        await milestonesRepository.CreateAsync(milestone, ct);

        logger.LogInformation(
            "Milestone {MilestoneId} created for project {ProjectId}",
            milestone.Id,
            milestone.ProjectId
        );

        return MapToDto(milestone);
    }

    /* ===================== HELPERS ===================== */

    private static Milestone BuildMilestone(CreateMilestoneCommand request, int order)
    {
        return new Milestone
        {
            Id = Guid.NewGuid(),
            ProjectId = request.ProjectId,
            Name = string.IsNullOrWhiteSpace(request.Dto.Name)
                ? request.Dto.TargetAmount.ToString("N0")
                : request.Dto.Name.Trim(),

            TargetAmount = request.Dto.TargetAmount,
            Order = order,
            DueDate = request.Dto.DueDate,
            Notes = request.Dto.Notes,

            AutoGenerated = false,
            Completed = false,
            CreatedAt = DateTime.UtcNow
        };
    }

    private static MilestoneDto MapToDto(Milestone m) =>
        new()
        {
            Id = m.Id,
            ProjectId = m.ProjectId,
            Name = m.Name,
            TargetAmount = m.TargetAmount,
            Order = m.Order,
            DueDate = m.DueDate,
            Notes = m.Notes,
            AutoGenerated = m.AutoGenerated,
            Completed = m.Completed,
            CreatedAt = m.CreatedAt
        };
}