using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MediatR;
using PlanWriter.Domain.Entities;
using PlanWriter.Domain.Events;
using PlanWriter.Domain.Interfaces.ReadModels.Milestones;
using PlanWriter.Domain.Interfaces.Repositories;

namespace PlanWriter.Application.Milestones.Handlers;

public class GenerateAutoMilestonesOnProgressHandler(
    IMilestonesRepository milestonesRepository, 
    IProjectRepository projectRepository,
    IMilestonesReadRepository milestonesReadRepository)
    : INotificationHandler<ProjectProgressAdded>
{
    public async Task Handle(ProjectProgressAdded notification, CancellationToken ct)
    {
        var project = await projectRepository.GetProjectById(notification.ProjectId);

        if (project?.WordCountGoal is null || project.WordCountGoal <= 0)
            return;

        var goal = project.WordCountGoal.Value;

        var existing =
            await milestonesReadRepository
                .GetByProjectIdAsync(notification.ProjectId, ct);

        var now = DateTime.UtcNow;

        var autoMilestones = new[]
        {
            (0.25, "25%", 100),
            (0.50, "50%", 200),
            (0.75, "75%", 300),
            (1.00, "100%", 400)
        };

        foreach (var (percent, name, order) in autoMilestones)
        {
            if (existing.Any(m => m.AutoGenerated && m.Name == name))
                continue;

            var target = (int)Math.Round(goal * percent);

            var milestone = new Milestone
            {
                Id = Guid.NewGuid(),
                ProjectId = notification.ProjectId,
                Name = name,
                TargetAmount = target,
                Order = order,
                AutoGenerated = true,
                Completed = notification.NewTotal >= target,
                CompletedAt = notification.NewTotal >= target ? now : null,
                CreatedAt = now
            };

            await milestonesRepository.CreateAsync(milestone, ct);
        }
    }
}
